version: 2.1

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test

