#!/bin/sh

linter='eslint'

if [[ ! -x "$(yarn bin)/$linter" ]]; then
  echo "please run `yarn` to install $linter."
  echo "please \`yarn\` to install $linter for this pre-commit hook"
  exit 1
fi

repo=$(basename $(git rev-parse --show-toplevel))
changed_files=''
for file in $(git diff --name-only --cached --diff-filter=d | grep '^tests\|src/.*\.js$'); do
  changed_files="$changed_files $file"
done
changed_files=$( echo "$changed_files" | sed 's/^ //' )

if [[ ! "$changed_files" ]]; then
  echo "Skipping $linter -- no js files are staged. 👍"
  echo
  exit 0
fi

echo "linting changes to /src ..."
echo "$changed_files"
"$(yarn bin)/$linter" $changed_files

if [[ "$?" == 0 ]]; then
  echo "\033[32m$linter passed\033[0m"
else
  echo "\033[41m$linter failed\033[0m"
  exit 1
fi
